
export const CRASH_EVENT = 'CRASH_EVENT';

export const PACKETS_RECEIVED_EVENT = 'PACKETS_RECEIVED_EVENT' // TODO Remove

export const COMMON_LOG_MESSAGES_RECEIVED_EVENT = 'COMMON_LOG_MESSAGES_RECEIVED_EVENT';
export const HTTP_DATA_PROCESSED_EVENT = 'HTTP_DATA_PROCESSED_EVENT';
export const SNAPSHOT_REPORT_CREATED_EVENT = 'SNAPSHOT_REPORT_CREATED_EVENT';

export const NUMBER_OF_REQUESTS_ALERT_THRESHOLD = 120;
export const GENERATE_TRAFFIC_POLLING_INTERVAL_MILLIS = 500;
export const LONG_DURATION_IN_MILLIS = 120 * 1000;
export const SHORT_DURATION_IN_MILLIS = 10 * 1000;
export const SIGNIFICANT_TRAFFIC_MULTIPLIER = 2;
export const PORT = 8080;
export const IP_ADDRESS_TO_LISTEN = '0.0.0.0';