
export const CRASH_EVENT = 'CRASH_EVENT';

export const PACKETS_RECEIVED_EVENT = 'PACKETS_RECEIVED_EVENT' // TODO Remove

export const COMMON_LOG_MESSAGES_RECEIVED_EVENT = 'COMMON_LOG_MESSAGES_RECEIVED_EVENT';
export const HTTP_DATA_PROCESSED_EVENT = 'HTTP_DATA_PROCESSED_EVENT';
export const SNAPSHOT_REPORT_CREATED_EVENT = 'SNAPSHOT_REPORT_CREATED_EVENT';